[tool.bumpversion]
commit = false
tag = false
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)(?:-(?P<prerelease>[0-9A-Za-z.-]+))?"
serialize = [
  "{major}.{minor}.{patch}-{prerelease}",
  "{major}.{minor}.{patch}"
]

[[tool.bumpversion.files]]
filename = "VERSION"

[[tool.bumpversion.files]]
filename = "CHANGELOG.md"
search = "## Unreleased"
replace = "## {new_version} - {now:%Y-%m-%d}"
