all:
  hosts:
    demo-single-node-aarch64:
      ansible_host: 10.0.0.11
  children:
    initial_controller:
      hosts:
        demo-single-node-aarch64:
    controllers:
      hosts:
    workers:
      hosts:
    workers_to_join:
      hosts:
  vars:
    ansible_user: root
    artifacts_dir: "{{ inventory_dir }}/artifacts/demo-single-node-aarch64"
    nixos_flake: ..
    skip_rook_ceph: true
