all:
  hosts:
    demo-single-node:
      ansible_host: 192.0.2.10
  children:
    initial_controller:
      hosts:
        demo-single-node:
    controllers:
      hosts:
    workers:
      hosts:
    workers_to_join:
      hosts:
  vars:
    ansible_user: root
    artifacts_dir: "{{ inventory_dir }}/artifacts/demo-single-node"
    nixos_flake: "{{ inventory_dir }}/.."
    skip_rook_ceph: true
    cilium_helmrelease_path: "../kubernetes/cluster-0/base-apps/kube-system/cilium/app/helmrelease.yaml"
    cilium_values_files:
      - "../kubernetes/cluster-0/base-apps/kube-system/cilium/app/values.yaml"
      - "../kubernetes/cluster-0/base-apps/kube-system/cilium/app/values-no-dashboards.yaml"
    openebs_helmrelease_path: "../kubernetes/cluster-0/base-apps/openebs/openebs/app/helmrelease.yaml"
    openebs_values_files:
      - "../kubernetes/cluster-0/base-apps/openebs/openebs/app/values.yaml"
